# -*- coding: utf-8 -*-
"""Ex01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HTB6WiPSM1gYvhEicv9y34-fnbVbINVx

# 요트다이스 만들기_02 aka.야추다이스

##### Small Straight : 이어지는 주사위 눈이 4개 이상일 때. 고정 15점. ex) 1 2 3 4 6, 1 3 4 5 6
"""

import random

# dice1 = int(random.random()*6+1)
# dice2 = int(random.random()*6+1)
# dice3 = int(random.random()*6+1)
# dice4 = int(random.random()*6+1)
# dice5 = int(random.random()*6+1)
point = 0

if dice1 == dice2-1 == dice3-2 == dice4-3:
  point += 15
elif dice2 == dice3-1 == dice4-2 == dice5-3:
  point += 15
elif dice1==dice2+1==dice3+2==dice4+3:
  point += 15
elif dice2==dice3+1==dice4+2==dice5+3:
  point += 15


print(dice1,dice2,dice3,dice4,dice5)
print(point)

"""##### Large Straight : 이어지는 주사위 눈이 5개일 때. 고정 30점. ex) 1 2 3 4 5, 2 3 4 5 6"""

dice1 = int(random.random()*6+1)
dice2 = int(random.random()*6+1)
dice3 = int(random.random()*6+1)
dice4 = int(random.random()*6+1)
dice5 = int(random.random()*6+1)

point = 0

if  dice1==dice2+1==dice3+2==dice4+3==dice5==4:
  point += 30
elif dice1==dice2-1==dice3-2==dice4-3==dice5-4:
    point += 30

print(dice1,dice2,dice3,dice4,dice5)
print(point)